config/routes.rb
Rails.application.routes.draw do
  resources :dashboard, only: :index

  resources :courses, except: :show

  resources :institutions

  resources :evaluations, only: :index

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)

      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end

      results
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :evaluations, dependent: :restrict_with_exception
  has_many :institutions, through: :evaluations

  validates :name, presence: true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  include Filterable

  belongs_to :course
  belongs_to :institution

  validates :course, :institution, :students_average_score, :course_score, presence: true
  validates :students_average_score, :course_score,
    numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }

  delegate :name, to: :course, prefix: true
  delegate :name, :score, to: :institution, prefix: true
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :evaluations, dependent: :destroy
  has_many :courses, through: :evaluations

  validates :name, presence: true
  validates :score, presence: true, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }

  accepts_nested_attributes_for :evaluations, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    if params[:without_pagination].present?
      @courses = Course.all
    else
      @courses = Course.all.paginate(page: params[:page], per_page: 30)
    end

    respond_with @courses
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_url, notice: 'Course successful created.'
    else
      render :new
    end
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      redirect_to courses_url, notice: 'Course successful updated.'
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])

    @course.destroy

    redirect_to courses_url, notice: 'Course successful removed.'
  end

  def destroy
    @course = Course.find(params[:id])

    begin
      @course.destroy
      redirect_to courses_url, notice: 'Course successful removed.'
    rescue ActiveRecord::DeleteRestrictionError
      redirect_to(
        courses_url(@course),
        alert: 'Could not remove. Records depend on this course.'
      )
    end
  end

  private

  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  def index
    @evaluations =
      evaluation_query
        .all
        .filter(
          params.slice(
            :institution_name,
            :course_name,
            :institution_score,
            :course_score,
            :students_average_score
          )
        )
        .includes(:course, :institution)
        .institution_score_desc

    respond_with @evaluations
  end

  private

  def evaluation_query
    @evaluation_query ||= EvaluationQuery.new
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  def index
    @institutions = Institution.all.paginate(page: params[:page], per_page: 30)
  end

  def show
    @institution = Institution.find(params[:id])

    respond_with @institution
  end

  def new
    @institution = Institution.new
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def create
    @institution = Institution.new(institution_params)

    @institution.save

    respond_with @institution
  end

  def update
    @institution = Institution.find(params[:id])

    @institution.update(institution_params)

    respond_with @institution
  end

  def destroy
    @institution = Institution.find(params[:id])

    @institution.destroy

    redirect_to institutions_url, notice: 'Institution successful removed.'
  end

  private

  def institution_params
    params.require(:institution).permit(
      :name,
      :score,
      evaluations_attributes: [
        :id,
        :course_id,
        :course_score,
        :students_average_score,
        :_destroy
      ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_if_controller(name)
    return if controller_name != name

    'active'
  end
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <%= render 'shared/error_messages', object: @course %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <%= f.submit nil, class: 'btn btn-success', data: { disable_with: 'Saving...' } %>

  <%= link_to 'Back', courses_path, class: 'btn btn-secondary' %>
<% end %>

app/views/courses/edit.html.erb
<h3>Edit Course</h3>

<%= render 'form' %>

app/views/courses/index.html.erb
<h3>Courses <%= link_to 'New Course', new_course_path, class: 'btn btn-primary btn-sm' %></h3>

<table class="table table-striped">
  <colgroup>
    <col width="80%">
    <col>
  </colgroup>

  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @courses.each do |course| %>
      <tr id="course_<%= course.id %>">
        <td><%= course.name %></td>
        <td>
          <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Remove',
            course_path(course),
            method: :delete,
            data: { confirm: 'Are sure?' },
            class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end.blank? %>
      <tr class="text-center">
        <td colspan="2">Click <%= link_to 'here', new_course_path %> to create a course.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @courses, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/courses/new.html.erb
<h3>New Course</h3>

<%= render 'form' %>

app/views/dashboard/index.html.erb
<div id="dashboard-app"></div>

<%= content_for :footer_javascript do %>
  <%= javascript_pack_tag 'dashboard/entry' %>
<% end %>

app/views/institutions/_form.html.erb
<div id="institution-form-app"></div>

<%= content_for :footer_javascript do %>
  <script>
    window.institutionId = <%== @institution.id.to_json %>;
  </script>

  <%= javascript_pack_tag 'institution_form/entry' %>
<% end %>

app/views/institutions/edit.html.erb
<%= render 'form' %>

app/views/institutions/index.html.erb
<h3>
  Institutions <%= link_to 'New Institution', new_institution_path, class: 'btn btn-primary btn-sm' %>
</h3>

<table class="table table-striped">
  <colgroup>
    <col width="80%">
    <col>
  </colgroup>

  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @institutions.each do |institution| %>
      <tr id="institution_<%= institution.id %>">
        <td><%= institution.name %></td>
        <td>
          <%= link_to 'Edit', edit_institution_path(institution), class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Remove',
            institution_path(institution),
            method: :delete,
            data: { confirm: 'Are sure?' },
            class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end.blank? %>
      <tr class="text-center">
        <td colspan="2">Click <%= link_to 'here', new_institution_path %> to create a institution.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @institutions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/institutions/new.html.erb
<%= render 'form' %>

app/views/layouts/_flash_notice.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">AppProva</a>

  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= active_link_if_controller('dashboard') %>">
        <a class="nav-link" href="/">Dashboard</a>
      </li>

      <li class="nav-item <%= active_link_if_controller('courses') %>">
        <%= link_to 'Courses', courses_path, class: 'nav-link' %>
      </li>

      <li class="nav-item <%= active_link_if_controller('institutions') %>">
        <%= link_to 'Institutions', institutions_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppProvaTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_notice' %>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :footer_javascript %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <p>
      <strong>
        <%= pluralize(object.errors.count, "error") %> prevented this record from being saved:
      </strong>
    </p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>